use std::path::Path;

use crate::errors::ProvisionError;

pub async fn ensure_eula(runtime_dir: &Path) -> Result<(), ProvisionError> {
    let eula_path = runtime_dir.join("eula.txt");
    let content = "# Generated by atlas-runnerd\neula=true\n";
    tokio::fs::write(&eula_path, content).await?;
    Ok(())
}
